name: IGEL App Feed Daily
on:
  schedule:
    - cron: "5 7 * * *"   # 07:05 UTC daily
  workflow_dispatch: {}
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure jq
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Build feed
        run: |
          chmod +x scripts/build_feed.sh
          bash scripts/build_feed.sh

      - name: Commit artifacts
        run: |
          git config user.name "igel-bot"
          git config user.email "bot@example.com"
          git add -A
          git commit -m "Daily IGEL app feed snapshot $(date -u +%F)" || echo "No changes"
          git push || true

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          cp -f feed/latest.json public/latest.json
          cp -f feed/latest.min.json public/latest.min.json
          if [ -f feed/summary_latest.txt ]; then cp -f feed/summary_latest.txt public/summary_latest.txt; fi
          NOW="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          cat > public/index.html <<'HTML'
<!doctype html>
<meta charset="utf-8">
<title>IGEL App Feed</title>
<style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:2rem;max-width:60rem}code{background:#f5f5f5;padding:.2rem .4rem;border-radius:.25rem}</style>
<h1>IGEL App Feed</h1>
<p>Daily snapshots of <code>https://app.igel.com/api/applications</code>.</p>
<ul>
  <li><a href="latest.json">latest.json</a> — full snapshot</li>
  <li><a href="latest.min.json">latest.min.json</a> — {name, displayName, version, publishedAt}</li>
  <li><a href="summary_latest.txt">summary_latest.txt</a> — diff vs previous</li>
</ul>
<p>Updated: <!--UPDATED--></p>
HTML
          sed -i "s/<!--UPDATED-->/$NOW/" public/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
